#!/usr/bin/env python3
"""
Does an acquisition batch label leak into the WSI embedding?

This is the diagnostic that decides what the robustness pack actually has to
correct for. It is confound_check.py's "Check B" idea (does TMT plex predict the
WSI PCs) generalised to the acquisition axes recovered from the SVS headers.

confound_check.py itself is not reusable here: it hardcodes the ccRCC purity
markers (CA9 / NDUFA4L2 / PAX8) and reads the pre-tumor-only residual_results.csv
by a fixed name. This script deliberately touches neither purity nor prior
results -- it only asks whether batch structure is visible in the embedding.

Statistic per (axis, PC): eta^2, the fraction of that PC's variance lying between
batch groups. Significance by permuting the batch labels (group sizes preserved,
so the null automatically accounts for axes with many small groups, which would
otherwise inflate eta^2). One shared set of permutations across PCs.

Reading the output:
  - no axis significant  -> strong negative evidence; the pack can be light
  - some axis significant -> that axis is what stage 3 must residualise against

Usage: batch_leak_check.py <cancer> [axis ...]
Output: <cohort>/results/batch_leak_results.csv
"""
import hashlib
import os
import re
import sys
from collections import Counter

import numpy as np
import pandas as pd

ROOT = "/public/home/fjhui/ZW"
SCRIPTS = f"{ROOT}/scripts"
PIN = f"{SCRIPTS}/pinned"
META = f"{SCRIPTS}/slide_acquisition_meta.tsv"

PROTEIN = {
    "ccrcc": None,  # resolved by glob below
    "ucec": None, "pdac": None, "gbm": None, "luad": None,
}

N_PCS = 20
N_PERM = 2000
MIN_GROUP = 3          # batches smaller than this are pooled into "_small"
MIN_LEVELS = 2
RNG = np.random.RandomState(0)

# --- plex / embedding-medium axes (2026-10-02 post hoc patch) ------------------
# Governed by review/POSTHOC_BATCH_AXES_PRESPEC_2026-10-02.md section P (plex)
# and section M (medium). Inputs are built locally (their scoping/PathDB sources
# do not exist on the HPC) by server_export/scripts/build_pinned_plex_maps.py
# and build_pinned_slide_medium.py, then uploaded to pinned/ on the HPC. The
# plex axis FATALs if any analysed case lacks a label (a silently
# partial-coverage plex axis would be worse than no axis at all); the medium
# axis is omitted, not fabricated, for a cohort with no pinned
# slide_embedding_medium.tsv.
PLEX_SHA256 = {
    "ccrcc": "bbc400d33a5fea38380bc68226b2c21624ca7f31fbec07566264c2da2df401a6",
    "luad": "014868ad61a5cfbe1cc112d603e5d2d669ddd82f03442e3f998cbd97170b616e",
    "ucec": "e3f383d85f11a6e35a63676ffbdebbd7e7bbad71bed38a199a594772ae141f03",
    "gbm": "e0aa9e78c7bf1edf8cc67fd7995037fc09327822e3163f882751beaf55589b3a",
    "pdac": "c612c808a7a55134f8e393613c55eb56d9443a2c6863abb6b5c798a871710099",
}
MEDIUM_SHA256 = "36783b539e14f3bad73d59d9769f7dd2d01ea21d08f0cd4d79dbfde48d098ef1"


def _sha256(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        h.update(f.read())
    return h.hexdigest()


def _assert_sha256(path, expected, label):
    got = _sha256(path)
    if got != expected:
        sys.exit(f"FATAL: sha256 mismatch for {label}: got={got} want={expected} "
                  f"({path}). Refusing to label batches from an unverified "
                  f"pinned input.")
    return got


def cohort_paths(cancer):
    # Manifests are read from scripts/pinned/, not scripts/. scripts/ is shared
    # with other people on this account and the legacy looser builders write the
    # same filenames: on 2026-09-01 a concurrent run of build_slide_map.py and
    # build_aliquot_xwalk.py replaced the UCEC and PDAC inputs mid-session,
    # re-admitting adjacent-normal slides and cell-line aliquots and quietly
    # contaminating every job that started after it. PIN holds this pipeline's
    # verified copies; the shared files are left alone.
    import glob
    suffix = "" if cancer == "ccrcc" else f"_{cancer}"
    if cancer == "ccrcc":
        root = ROOT
        emb = f"{ROOT}/WSI/emb/ccrcc_real"
    else:
        root = f"{ROOT}/{cancer}"
        emb = f"{root}/WSI/emb"
    slide_map = f"{PIN}/slide_type_map{suffix}.tsv"
    xwalk = f"{PIN}/aliquot_to_case_tumor{suffix}.tsv"
    rna_manifest = f"{PIN}/manifest_rna_tumor{suffix}.tsv"
    for p in (slide_map, xwalk, rna_manifest):
        if not os.path.exists(p):
            raise FileNotFoundError(
                f"pinned input missing: {p}. Rebuild it with MORPHO_MAP_DIR={PIN} "
                f"rather than falling back to the shared scripts/ copy, which may "
                f"have been regenerated by the legacy builders.")
    return dict(root=root, emb=emb, slide_map=slide_map, xwalk=xwalk,
                rna_manifest=rna_manifest, protein=find_proteome(root),
                out=f"{root}/results")


def find_proteome(root):
    """Pick the TMT proteome table, not whatever sorts first.

    ZW/omics/protein/ holds the ccRCC proteome AND a .summary.tsv sibling AND a
    few stray LUAD manifests that were dropped there. A plain
    sorted(glob("*.tsv"))[0] picks CPTAC3_..._Proteome.summary.tsv, whose columns
    are spectral counts rather than "<aliquot> Log Ratio", so load_protein_matrix
    matches zero aliquots and the cohort silently collapses to 0 patients --
    which is exactly how the first ccRCC sitepack run failed.
    """
    import glob as _g
    d = f"{root}/omics/protein"
    for pattern in (f"{d}/*Proteome*.tmt*.tsv", f"{d}/*.tmt*.tsv"):
        hits = sorted(p for p in _g.glob(pattern) if ".summary." not in p)
        if hits:
            return hits[0]
    hits = sorted(p for p in _g.glob(f"{d}/*.tsv")
                  if not any(k in os.path.basename(p)
                             for k in (".summary.", "manifest", "slide_type_map",
                                       "aliquot_to_case")))
    return hits[0] if hits else ""


def load_wsi(cancer, paths):
    """Per-case mean-pooled tumor embedding, exactly as residual_analysis does."""
    os.environ.update(
        MORPHO_ROOT=paths["root"],
        MORPHO_RNA_MANIFEST=paths["rna_manifest"],
        MORPHO_ALIQUOT_XWALK=paths["xwalk"],
        MORPHO_SLIDE_MAP=paths["slide_map"],
        MORPHO_PROTEIN_TSV=paths["protein"],
        MORPHO_WSI_EMB_DIR=paths["emb"],
        MORPHO_OUT=paths["out"],
    )
    sys.path.insert(0, SCRIPTS)
    import residual_analysis as ra
    return ra.load_wsi_embeddings(), ra


def case_batch_labels(cancer, paths, cases, strict_plex=True):
    """Assign each case one label per acquisition axis, from the tumor slides
    that actually entered its mean-pooled embedding.

    strict_plex: abort if any case in `cases` has no plex label. True is correct
    for the analysed population (residual_analysis_sitepack passes the RNA x
    protein x WSI intersection, which is what the pinned maps were built from).
    The diagnostic in main() passes the WSI-embedding index, a superset that
    legitimately contains cases with no TMT aliquot and so no plex, and sets
    this False so a scope mismatch reports itself instead of killing the run.
    """
    meta = pd.read_csv(META, sep="\t", dtype=str).fillna("")
    meta = meta[meta["cohort"] == cancer]
    smap = pd.read_csv(paths["slide_map"], sep="\t", dtype=str)
    tumor = set(smap.loc[smap["sample_type"] == "Primary Tumor", "slide_submitter_id"])
    present = {os.path.basename(p)[:-3] for p in __import__("glob").glob(paths["emb"] + "/*.pt")}
    used = tumor & present
    meta = meta[meta["slide_submitter_id"].isin(used)]

    axes = {}
    for axis, col in [("scanner", "scanner_id"), ("operator", "operator_uuid"),
                      ("quarter", "scan_quarter"), ("mpp", "mpp")]:
        lab, purity = {}, {}
        for case, grp in meta.groupby("case_submitter_id"):
            vals = [v for v in grp[col].tolist() if v]
            if not vals:
                continue
            c = Counter(vals).most_common()
            lab[case] = c[0][0]
            purity[case] = c[0][1] / len(vals)
        axes[axis] = (lab, purity)

    # accrual stream, available for every CPTAC case without any metadata
    axes["cohort_stream"] = ({c: c[:3] for c in cases}, {c: 1.0 for c in cases})

    # --- plex axis (PLEX_SHA256 above) ------------------------------------
    # Pinned per-cohort map ONLY -- do NOT fall back to the legacy
    # scripts/case_to_plex.tsv first (ccRCC-only; that ordering silently
    # skipped the plex axis for the other four cohorts). FATAL if any
    # analysed case in `cases` lacks a label.
    plex_path = f"{PIN}/case_to_plex_{cancer}.tsv"
    if os.path.exists(plex_path):
        if cancer not in PLEX_SHA256:
            sys.exit(f"FATAL: no pinned sha256 registered for plex cohort "
                      f"{cancer!r}; add it to PLEX_SHA256 before using "
                      f"{plex_path}.")
        _assert_sha256(plex_path, PLEX_SHA256[cancer], f"case_to_plex_{cancer}")
        p = pd.read_csv(plex_path, sep="\t", dtype=str)
        lab = dict(zip(p["case_id"], p["plex"]))
        missing = sorted(set(cases) - set(lab))
        if missing and strict_plex:
            sys.exit(f"FATAL: {len(missing)} analysed case(s) for {cancer} "
                      f"have no plex label in {plex_path}: "
                      f"{missing[:10]}{' ...' if len(missing) > 10 else ''}")
        if missing:
            print(f"  plex axis ({cancer}): {len(missing)} of {len(cases)} cases "
                  f"given have no plex label and are left out of this axis "
                  f"(expected here: the caller passed a WSI-only superset of the "
                  f"analysed set): "
                  f"{missing[:10]}{' ...' if len(missing) > 10 else ''}")
        axes["plex"] = (lab, {c: 1.0 for c in lab})
    else:
        print(f"  (no pinned plex map for {cancer} at {plex_path}, axis omitted)")

    # --- embedding-medium axis (MEDIUM_SHA256 above) ----------------------
    # Per-case FFPE/OCT/mixed/unknown label, joined by slide_submitter_id to
    # the SAME `used` Primary-Tumor-with-embedding slide set already computed
    # above for scanner/operator/quarter/mpp. Omitted (not fabricated) if the
    # pinned file is absent.
    medium_path = f"{PIN}/slide_embedding_medium.tsv"
    if os.path.exists(medium_path):
        _assert_sha256(medium_path, MEDIUM_SHA256, "slide_embedding_medium")
        med = pd.read_csv(medium_path, sep="\t", dtype=str).fillna("")
        medium_of_slide = dict(zip(med["slide_submitter_id"], med["embedding_medium"]))

        smap_used = smap[smap["slide_submitter_id"].isin(used)]
        slide_to_case = dict(zip(smap_used["slide_submitter_id"],
                                  smap_used["case_submitter_id"]))
        case_used_slides = {}
        for s in sorted(used):
            c = slide_to_case.get(s)
            if c is None:
                continue
            case_used_slides.setdefault(c, []).append(s)

        lab = {}
        n_slides_total = 0
        n_slides_unjoined = 0
        for c, slides in case_used_slides.items():
            meds = []
            for s in slides:
                n_slides_total += 1
                m = medium_of_slide.get(s, "")
                if not m:
                    n_slides_unjoined += 1
                meds.append(m or None)
            if any(m is None for m in meds):
                lab[c] = "unknown"
            else:
                levels = set(meds)
                lab[c] = levels.pop() if len(levels) == 1 else "mixed"

        axes["medium"] = (lab, {c: 1.0 for c in lab})
        level_counts = Counter(lab.values())
        fail_rate = (n_slides_unjoined / n_slides_total) if n_slides_total else float("nan")
        print(f"  medium axis ({cancer}): per-case level counts "
              f"{dict(level_counts)}; slide join failure {n_slides_unjoined}/"
              f"{n_slides_total} = {fail_rate:.3f}")
    else:
        print(f"  (no pinned medium map at {medium_path}, axis omitted)")

    return axes


def eta2(x, codes, k):
    """Between-group variance fraction of a single PC."""
    grand = x.mean()
    ss_tot = ((x - grand) ** 2).sum()
    if ss_tot <= 0:
        return 0.0
    ss_between = 0.0
    for g in range(k):
        sel = codes == g
        n = sel.sum()
        if n:
            ss_between += n * (x[sel].mean() - grand) ** 2
    return ss_between / ss_tot


def bh_fdr(p):
    p = np.asarray(p, dtype=float)
    n = len(p)
    order = np.argsort(p)
    ranked = p[order] * n / (np.arange(n) + 1)
    ranked = np.minimum.accumulate(ranked[::-1])[::-1]
    out = np.empty(n)
    out[order] = np.clip(ranked, 0, 1)
    return out


def main():
    cancer = sys.argv[1]
    want = sys.argv[2:] or None
    paths = cohort_paths(cancer)
    print(f"=== batch leak check: {cancer} ===")
    for k, v in paths.items():
        print(f"  {k}: {v}")

    wsi, _ra = load_wsi(cancer, paths)
    cases = list(wsi.index)
    from sklearn.decomposition import PCA
    n_pcs = min(N_PCS, len(cases) - 1, wsi.shape[1])
    # svd_solver="full": at this matrix shape sklearn's auto solver is randomized
    # SVD with random_state=None and is not reproducible (measured: up to 24.4
    # difference in scores between two identical calls).
    pcs = PCA(n_components=n_pcs, svd_solver="full").fit_transform(wsi.values)
    print(f"  WSI PCs: {pcs.shape}")

    axes = case_batch_labels(cancer, paths, cases, strict_plex=False)
    rows = []
    for axis, (lab, purity) in axes.items():
        if want and axis not in want:
            continue
        raw = [lab.get(c, "") for c in cases]
        cov = sum(1 for v in raw if v)
        counts = Counter(v for v in raw if v)
        # pool tiny batches so a handful of singletons cannot masquerade as signal
        pooled = [v if (v and counts[v] >= MIN_GROUP) else ("_small" if v else "")
                  for v in raw]
        keep = np.array([bool(v) for v in pooled])
        levels = sorted(set(v for v in pooled if v))
        mixed = [c for c in cases if purity.get(c, 1.0) < 1.0]
        print(f"\n--- axis {axis}: coverage {cov}/{len(cases)} cases, "
              f"{len(counts)} raw levels -> {len(levels)} after pooling(min {MIN_GROUP}); "
              f"{len(mixed)} cases have slides from >1 batch")
        print(f"    level sizes: {dict(Counter(v for v in pooled if v).most_common(12))}")
        if len(levels) < MIN_LEVELS or keep.sum() < 20:
            print(f"    SKIP: only {len(levels)} usable level(s) / {keep.sum()} cases "
                  f"-> nothing to confound with on this axis")
            rows.append(dict(cohort=cancer, axis=axis, pc=-1, n=int(keep.sum()),
                             n_levels=len(levels), eta2=np.nan, pval=np.nan,
                             fdr=np.nan, note="degenerate_axis"))
            continue

        idx = {lv: i for i, lv in enumerate(levels)}
        codes = np.array([idx[v] for v in np.array(pooled)[keep]])
        X = pcs[keep]
        k = len(levels)
        perms = [RNG.permutation(len(codes)) for _ in range(N_PERM)]
        pvals, obs = [], []
        for j in range(X.shape[1]):
            x = X[:, j]
            e = eta2(x, codes, k)
            null = np.array([eta2(x, codes[p], k) for p in perms])
            pv = (np.sum(null >= e) + 1) / (N_PERM + 1)
            obs.append(e)
            pvals.append(pv)
        fdr = bh_fdr(pvals)
        nsig = int(np.sum(fdr < 0.05))
        print(f"    max eta2 = {max(obs):.4f} (PC{int(np.argmax(obs)) + 1}); "
              f"PCs with FDR<0.05: {nsig}/{X.shape[1]}")
        for j in range(X.shape[1]):
            rows.append(dict(cohort=cancer, axis=axis, pc=j + 1, n=int(keep.sum()),
                             n_levels=k, eta2=obs[j], pval=pvals[j], fdr=fdr[j],
                             note=""))

    out = os.path.join(paths["out"], "batch_leak_results.csv")
    os.makedirs(paths["out"], exist_ok=True)
    pd.DataFrame(rows).to_csv(out, index=False)
    print(f"\nwrote {out}")

    df = pd.DataFrame(rows)
    real = df[df["pc"] > 0]
    if len(real):
        print("\n=== SUMMARY (axes that leak into the embedding) ===")
        for axis, g in real.groupby("axis"):
            print(f"  {axis:<16} max eta2={g['eta2'].max():.4f}  "
                  f"sig PCs={int((g['fdr'] < 0.05).sum())}/{len(g)}")


if __name__ == "__main__":
    main()
