#!/usr/bin/env python3
"""
Does an acquisition batch label leak into the WSI embedding?

This is the diagnostic that decides what the robustness pack actually has to
correct for. It is confound_check.py's "Check B" idea (does TMT plex predict the
WSI PCs) generalised to the acquisition axes recovered from the SVS headers.

confound_check.py itself is not reusable here: it hardcodes the ccRCC purity
markers (CA9 / NDUFA4L2 / PAX8) and reads the pre-tumor-only residual_results.csv
by a fixed name. This script deliberately touches neither purity nor prior
results -- it only asks whether batch structure is visible in the embedding.

Statistic per (axis, PC): eta^2, the fraction of that PC's variance lying between
batch groups. Significance by permuting the batch labels (group sizes preserved,
so the null automatically accounts for axes with many small groups, which would
otherwise inflate eta^2). One shared set of permutations across PCs.

Reading the output:
  - no axis significant  -> strong negative evidence; the pack can be light
  - some axis significant -> that axis is what stage 3 must residualise against

Usage: batch_leak_check.py <cancer> [axis ...]
Output: <cohort>/results/batch_leak_results.csv
"""
import os
import re
import sys
from collections import Counter

import numpy as np
import pandas as pd

ROOT = "/public/home/fjhui/ZW"
SCRIPTS = f"{ROOT}/scripts"
PIN = f"{SCRIPTS}/pinned"
META = f"{SCRIPTS}/slide_acquisition_meta.tsv"

PROTEIN = {
    "ccrcc": None,  # resolved by glob below
    "ucec": None, "pdac": None, "gbm": None, "luad": None,
}

N_PCS = 20
N_PERM = 2000
MIN_GROUP = 3          # batches smaller than this are pooled into "_small"
MIN_LEVELS = 2
RNG = np.random.RandomState(0)


def cohort_paths(cancer):
    # Manifests are read from scripts/pinned/, not scripts/. scripts/ is shared
    # with other people on this account and the legacy looser builders write the
    # same filenames: on 2026-09-01 a concurrent run of build_slide_map.py and
    # build_aliquot_xwalk.py replaced the UCEC and PDAC inputs mid-session,
    # re-admitting adjacent-normal slides and cell-line aliquots and quietly
    # contaminating every job that started after it. PIN holds this pipeline's
    # verified copies; the shared files are left alone.
    import glob
    suffix = "" if cancer == "ccrcc" else f"_{cancer}"
    if cancer == "ccrcc":
        root = ROOT
        emb = f"{ROOT}/WSI/emb/ccrcc_real"
    else:
        root = f"{ROOT}/{cancer}"
        emb = f"{root}/WSI/emb"
    slide_map = f"{PIN}/slide_type_map{suffix}.tsv"
    xwalk = f"{PIN}/aliquot_to_case_tumor{suffix}.tsv"
    rna_manifest = f"{PIN}/manifest_rna_tumor{suffix}.tsv"
    for p in (slide_map, xwalk, rna_manifest):
        if not os.path.exists(p):
            raise FileNotFoundError(
                f"pinned input missing: {p}. Rebuild it with MORPHO_MAP_DIR={PIN} "
                f"rather than falling back to the shared scripts/ copy, which may "
                f"have been regenerated by the legacy builders.")
    return dict(root=root, emb=emb, slide_map=slide_map, xwalk=xwalk,
                rna_manifest=rna_manifest, protein=find_proteome(root),
                out=f"{root}/results")


def find_proteome(root):
    """Pick the TMT proteome table, not whatever sorts first.

    ZW/omics/protein/ holds the ccRCC proteome AND a .summary.tsv sibling AND a
    few stray LUAD manifests that were dropped there. A plain
    sorted(glob("*.tsv"))[0] picks CPTAC3_..._Proteome.summary.tsv, whose columns
    are spectral counts rather than "<aliquot> Log Ratio", so load_protein_matrix
    matches zero aliquots and the cohort silently collapses to 0 patients --
    which is exactly how the first ccRCC sitepack run failed.
    """
    import glob as _g
    d = f"{root}/omics/protein"
    for pattern in (f"{d}/*Proteome*.tmt*.tsv", f"{d}/*.tmt*.tsv"):
        hits = sorted(p for p in _g.glob(pattern) if ".summary." not in p)
        if hits:
            return hits[0]
    hits = sorted(p for p in _g.glob(f"{d}/*.tsv")
                  if not any(k in os.path.basename(p)
                             for k in (".summary.", "manifest", "slide_type_map",
                                       "aliquot_to_case")))
    return hits[0] if hits else ""


def load_wsi(cancer, paths):
    """Per-case mean-pooled tumor embedding, exactly as residual_analysis does."""
    os.environ.update(
        MORPHO_ROOT=paths["root"],
        MORPHO_RNA_MANIFEST=paths["rna_manifest"],
        MORPHO_ALIQUOT_XWALK=paths["xwalk"],
        MORPHO_SLIDE_MAP=paths["slide_map"],
        MORPHO_PROTEIN_TSV=paths["protein"],
        MORPHO_WSI_EMB_DIR=paths["emb"],
        MORPHO_OUT=paths["out"],
    )
    sys.path.insert(0, SCRIPTS)
    import residual_analysis as ra
    return ra.load_wsi_embeddings(), ra


def case_batch_labels(cancer, paths, cases):
    """Assign each case one label per acquisition axis, from the tumor slides
    that actually entered its mean-pooled embedding."""
    meta = pd.read_csv(META, sep="\t", dtype=str).fillna("")
    meta = meta[meta["cohort"] == cancer]
    smap = pd.read_csv(paths["slide_map"], sep="\t", dtype=str)
    tumor = set(smap.loc[smap["sample_type"] == "Primary Tumor", "slide_submitter_id"])
    present = {os.path.basename(p)[:-3] for p in __import__("glob").glob(paths["emb"] + "/*.pt")}
    used = tumor & present
    meta = meta[meta["slide_submitter_id"].isin(used)]

    axes = {}
    for axis, col in [("scanner", "scanner_id"), ("operator", "operator_uuid"),
                      ("quarter", "scan_quarter"), ("mpp", "mpp")]:
        lab, purity = {}, {}
        for case, grp in meta.groupby("case_submitter_id"):
            vals = [v for v in grp[col].tolist() if v]
            if not vals:
                continue
            c = Counter(vals).most_common()
            lab[case] = c[0][0]
            purity[case] = c[0][1] / len(vals)
        axes[axis] = (lab, purity)

    # accrual stream, available for every CPTAC case without any metadata
    axes["cohort_stream"] = ({c: c[:3] for c in cases}, {c: 1.0 for c in cases})

    plex_path = f"{SCRIPTS}/case_to_plex.tsv"
    if os.path.exists(plex_path):
        try:
            p = pd.read_csv(plex_path, sep="\t", dtype=str)
            cc = p.columns[0]
            pc = p.columns[1]
            lab = dict(zip(p[cc], p[pc]))
            if len(set(lab) & set(cases)) >= 10:
                axes["plex"] = (lab, {c: 1.0 for c in lab})
        except Exception as e:
            print(f"  (plex map unreadable, skipped: {e})")
    return axes


def eta2(x, codes, k):
    """Between-group variance fraction of a single PC."""
    grand = x.mean()
    ss_tot = ((x - grand) ** 2).sum()
    if ss_tot <= 0:
        return 0.0
    ss_between = 0.0
    for g in range(k):
        sel = codes == g
        n = sel.sum()
        if n:
            ss_between += n * (x[sel].mean() - grand) ** 2
    return ss_between / ss_tot


def bh_fdr(p):
    p = np.asarray(p, dtype=float)
    n = len(p)
    order = np.argsort(p)
    ranked = p[order] * n / (np.arange(n) + 1)
    ranked = np.minimum.accumulate(ranked[::-1])[::-1]
    out = np.empty(n)
    out[order] = np.clip(ranked, 0, 1)
    return out


def main():
    cancer = sys.argv[1]
    want = sys.argv[2:] or None
    paths = cohort_paths(cancer)
    print(f"=== batch leak check: {cancer} ===")
    for k, v in paths.items():
        print(f"  {k}: {v}")

    wsi, _ra = load_wsi(cancer, paths)
    cases = list(wsi.index)
    from sklearn.decomposition import PCA
    n_pcs = min(N_PCS, len(cases) - 1, wsi.shape[1])
    # svd_solver="full": at this matrix shape sklearn's auto solver is randomized
    # SVD with random_state=None and is not reproducible (measured: up to 24.4
    # difference in scores between two identical calls).
    pcs = PCA(n_components=n_pcs, svd_solver="full").fit_transform(wsi.values)
    print(f"  WSI PCs: {pcs.shape}")

    axes = case_batch_labels(cancer, paths, cases)
    rows = []
    for axis, (lab, purity) in axes.items():
        if want and axis not in want:
            continue
        raw = [lab.get(c, "") for c in cases]
        cov = sum(1 for v in raw if v)
        counts = Counter(v for v in raw if v)
        # pool tiny batches so a handful of singletons cannot masquerade as signal
        pooled = [v if (v and counts[v] >= MIN_GROUP) else ("_small" if v else "")
                  for v in raw]
        keep = np.array([bool(v) for v in pooled])
        levels = sorted(set(v for v in pooled if v))
        mixed = [c for c in cases if purity.get(c, 1.0) < 1.0]
        print(f"\n--- axis {axis}: coverage {cov}/{len(cases)} cases, "
              f"{len(counts)} raw levels -> {len(levels)} after pooling(min {MIN_GROUP}); "
              f"{len(mixed)} cases have slides from >1 batch")
        print(f"    level sizes: {dict(Counter(v for v in pooled if v).most_common(12))}")
        if len(levels) < MIN_LEVELS or keep.sum() < 20:
            print(f"    SKIP: only {len(levels)} usable level(s) / {keep.sum()} cases "
                  f"-> nothing to confound with on this axis")
            rows.append(dict(cohort=cancer, axis=axis, pc=-1, n=int(keep.sum()),
                             n_levels=len(levels), eta2=np.nan, pval=np.nan,
                             fdr=np.nan, note="degenerate_axis"))
            continue

        idx = {lv: i for i, lv in enumerate(levels)}
        codes = np.array([idx[v] for v in np.array(pooled)[keep]])
        X = pcs[keep]
        k = len(levels)
        perms = [RNG.permutation(len(codes)) for _ in range(N_PERM)]
        pvals, obs = [], []
        for j in range(X.shape[1]):
            x = X[:, j]
            e = eta2(x, codes, k)
            null = np.array([eta2(x, codes[p], k) for p in perms])
            pv = (np.sum(null >= e) + 1) / (N_PERM + 1)
            obs.append(e)
            pvals.append(pv)
        fdr = bh_fdr(pvals)
        nsig = int(np.sum(fdr < 0.05))
        print(f"    max eta2 = {max(obs):.4f} (PC{int(np.argmax(obs)) + 1}); "
              f"PCs with FDR<0.05: {nsig}/{X.shape[1]}")
        for j in range(X.shape[1]):
            rows.append(dict(cohort=cancer, axis=axis, pc=j + 1, n=int(keep.sum()),
                             n_levels=k, eta2=obs[j], pval=pvals[j], fdr=fdr[j],
                             note=""))

    out = os.path.join(paths["out"], "batch_leak_results.csv")
    os.makedirs(paths["out"], exist_ok=True)
    pd.DataFrame(rows).to_csv(out, index=False)
    print(f"\nwrote {out}")

    df = pd.DataFrame(rows)
    real = df[df["pc"] > 0]
    if len(real):
        print("\n=== SUMMARY (axes that leak into the embedding) ===")
        for axis, g in real.groupby("axis"):
            print(f"  {axis:<16} max eta2={g['eta2'].max():.4f}  "
                  f"sig PCs={int((g['fdr'] < 0.05).sum())}/{len(g)}")


if __name__ == "__main__":
    main()
