"""Build SuppTable_c1ucec_plex.tex from
server_export/results/c1_ucec_plex/ucec_c1/results/posthoc/c1_ucec_plex_reread_result.json
(the single pre-specified run, LSF job 75740140, of
review/POSTHOC_UCEC_C1_PLEX_PRESPEC_2026-10-08.md).

Rounding follows section 4(g) of that file: AUC, null mean, null s.d., margin and p to
3 decimals, z to 2; if rounding would print a value on the other side of a threshold
(0.05 for p, 1.96 for z), decimals are added until it does not.
"""
import json
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parent
RES = ROOT / "server_export/results/c1_ucec_plex/ucec_c1/results/posthoc"
d = json.loads((RES / "c1_ucec_plex_reread_result.json").read_text(encoding="utf-8"))
assert d["governed_by"] == "review/POSTHOC_UCEC_C1_PLEX_PRESPEC_2026-10-08.md"
assert d["perms"] == 1000 and d["n_cases"] == 138 and d["K"] == 28


def guarded(x, nd, thr):
    """Round x to nd decimals, adding decimals while the rounded value crosses thr."""
    while True:
        s = f"{x:.{nd}f}"
        if (float(s) < thr) == (x < thr) or nd >= 8:
            return s
        nd += 1


def f3(x):
    return f"{x:.3f}"


def fp(p):
    return guarded(p, 3, 0.05)


def fz(z):
    return guarded(z, 2, 1.96)


B = d["perms"]

# Is the usable gene list of P3 identical to step 1's? (saved arrays of the same run)
npz_path = RES / "c1_ucec_plex_reread.npz"
same_genes = None
if npz_path.exists():
    z = np.load(npz_path)
    same_genes = bool(np.array_equal(z["genes"], z["genes_p3"])
                      and np.array_equal(z["sel_mask"], z["sel_mask_p3"]))
else:
    same_genes = all(d["P3"][k] == d["step1"][k] for k in ("n_usable", "n_selected", "n_background"))
assert same_genes, "P3 usable gene list differs from step 1; caption must be changed"


def tc(n):
    """Integer with a LaTeX thousands separator, for use inside math mode."""
    return f"{n:,}".replace(",", "{,}")


WORD = {6: "six", 10: "ten"}


def plex_no(name):
    return name[:2]


sizes = list(d["plex_strata"]["stratum_sizes"].values())
n8, n9 = sizes.count(8), sizes.count(9)
assert len(sizes) == 16 and n8 + n9 == 16 and d["plex_strata"]["n_cases_fixed"] == 0
p3sizes = d["P3"]["strata"]["stratum_sizes"]
p3_changed = {plex_no(k): v for k, v in p3sizes.items() if v != d["plex_strata"]["stratum_sizes"][k]}
assert p3_changed == {"16": 7}, p3_changed
P1, P2, P3, S1 = d["P1"], d["P2"], d["P3"], d["step1"]


def row(name, null, a, n, K):
    return (f"{name} & {null} & {n} & {K} & {f3(a['auc_obs'])} & "
            f"{f3(a['auc_null_mean'])}$\\pm${f3(a['auc_null_sd'])} & {f3(a['margin_auc'])} & "
            f"{fz(a['z_auc'])} & {fp(a['p_auc'])} ({a['exceedances_auc']}) & "
            f"{f3(a['rho_obs'])} & {f3(a['rho_null_mean'])}$\\pm${f3(a['rho_null_sd'])} & "
            f"{fp(a['p_rho'])} \\\\")


shift = P1["null_mean_shift_vs_unrestricted"]
lines = []
A = lines.append
A("% Supplementary Table: post hoc C1-UCEC re-read under a within-TMT-plex null,")
A("% governed by review/POSTHOC_UCEC_C1_PLEX_PRESPEC_2026-10-08.md, released publicly on GitHub")
A("% (commit bc66e6b, tag c1-ucec-posthoc-plex-prespec-2026-10-08) before the single run (LSF job 75740140).")
A("% Generated by make_supptable_c1ucec_plex.py from")
A("% server_export/results/c1_ucec_plex/ucec_c1/results/posthoc/c1_ucec_plex_reread_result.json.")
A("\\begin{table}[p]")
A("\\centering")
A("\\captionsetup{font={scriptsize,stretch=1.0}}")
A("\\caption{\\textbf{Post hoc re-read of the UCEC confirmatory test under a within-TMT-plex null.} "
  "Specified on 8 October 2026 (UTC) in a dated file released publicly before the single run "
  "(Supplementary Note~\\ref{snote:c1posthoc}); post hoc, and reported whatever the result. "
  "\\emph{Step 1}: the published test reproduced through the frozen code (unrestricted null); all "
  "fifteen published statistics matched before anything new was computed. "
  f"\\emph{{P1}} (the reading): the published selection set ($2{{,}}566$ genes, "
  f"${tc(S1['n_selected'])}$ usable; background ${tc(S1['n_background'])}$) against a null that permutes "
  f"patients only within the {d['plex_strata']['n_levels']} plexes ({WORD.get(n8, n8)} of $8$ patients, {WORD.get(n9, n9)} of $9$; "
  "none held fixed); its null mean lies "
  f"${'+' if shift >= 0 else '-'}{abs(shift):.3f}$ from step~1's and its s.d.\\ is "
  f"${P1['null_sd_ratio_vs_unrestricted']:.3f}$ times step~1's (a shift is not an attribution; block "
  "restriction raises a null mechanically). "
  f"\\emph{{P2}} (descriptive): the same set on morphology components residualised on "
  f"{P2['n_dummies']} plex dummies (plex {plex_no(P2['dropped_for_full_rank'])} dropped for full rank; "
  f"${100 * P2['pc_variance_retained']:.1f}\\%$ of component variance retained), with P1's draws. "
  f"\\emph{{P3}} (sensitivity): P1 without the two patients whose protein values may combine two "
  f"plexes (components refitted; plex 16 keeps $7$ patients; usable gene list identical to step~1), "
  "from a fresh generator with P1's seed. "
  f"Nulls: ${tc(B)}$ permutations (mean$\\pm$s.d.); one-sided $p$ = (1 + number of null values at or "
  "above the observed)$/1{,}001$, floor $0.001$; \\emph{exc.} = number of null AUCs at or above the "
  "observed; \\emph{Margin} = AUC minus its own null mean; $z$ = (AUC $-$ null mean)/s.d. Only P1's "
  "AUC $p$ is read; $\\rho$ and the other rows are reported, not read.}")
A("\\label{tab:c1ucecplex}")
A("\\scriptsize")
A("\\setlength{\\tabcolsep}{2.5pt}")
A("\\resizebox{\\textwidth}{!}{%")
A("\\begin{tabular}{llrrrrrrrrrr}")
A("\\toprule")
A("Arm & Null & $n$ & $K$ & AUC & Null & Margin & $z$ & $p$ (exc.) & $\\rho$ & $\\rho$ null & "
  "$p_{\\rho}$ \\\\")
A("\\midrule")
A(row("Step 1 (reproduced)", "unrestricted", S1, d["n_cases"], d["K"]))
A(row("P1 (reading)", "within plex", P1, d["n_cases"], d["K"]))
A(row("P2 (descriptive)", "within plex, plex-resid.", P2, d["n_cases"], d["K"]))
A(row("P3 (sensitivity)", "within plex", P3, P3["n_cases"], P3["K"]))
A("\\bottomrule")
A("\\end{tabular}}")
A("\\end{table}")
(ROOT / "SuppTable_c1ucec_plex.tex").write_bytes(("\n".join(lines) + "\n").encode("utf-8"))
print("wrote SuppTable_c1ucec_plex.tex")
