"""Build SuppTable_brca_ts.tex from
review/BRCA_TS_ARM_2026-10-08/setlevel/results/setlevel_result.csv
(the single pre-specified local read-out of review/POSTHOC_BRCA_TS_PRESPEC_2026-10-08.md,
with Amendment 1, review/POSTHOC_BRCA_TS_AMENDMENT1_2026-10-08.md).

Also read (read-only): setlevel_result.json (DX gate), the three per-gene summaries, the
pool manifest, the skip list and the two slide-QC tables brought back from the server
(the DX tile counts come from the full-density census, Amendment 1, item 2).
"""
import json
from collections import Counter
from pathlib import Path
from statistics import median

import pandas as pd

ROOT = Path(__file__).resolve().parent
ARM = ROOT / "review/BRCA_TS_ARM_2026-10-08"
BB = ARM / "bringback"

d = pd.read_csv(ARM / "setlevel/results/setlevel_result.csv")
meta = json.loads((ARM / "setlevel/results/setlevel_result.json").read_text(encoding="utf-8"))["meta"]
gate = meta["dx_gate"]
cases = meta["cases"]

summ = {
    "ts": pd.read_csv(BB / "results_ts/summary_brca_ts.csv").iloc[0],
    "ts_tile": pd.read_csv(BB / "results_ts/summary_brca_ts_tilepool.csv").iloc[0],
    "dx": pd.read_csv(BB / "results_dx_repro/summary_brca.csv").iloc[0],
    "dx_pub": pd.read_csv(BB / "results/summary_brca.csv").iloc[0],
}
qc_ts = pd.read_csv(BB / "results_ts/ts_slide_qc.tsv", sep="\t")
qc_dx = pd.read_csv(BB / "results/dx_slide_qc_dense.tsv", sep="\t")
pool = pd.read_csv(BB / "results_ts/pool_manifest_brca_ts.csv")
skips = [ln for ln in (BB / "ts_skipped_slides.txt").read_text(encoding="utf-8").splitlines() if ln.strip()]

ARM_NAME = {"ts": "TS (primary; slide-then-patient pooling)",
            "dx": "DX re-run (slide-then-patient pooling)",
            "ts_tile": "TS-tile (sensitivity; tile-weighted pooling)"}
SET_NAME = {"pub_k3": "Published, $\\geq3$ cohorts (primary)",
            "pub_k4": "Published, $\\geq4$ cohorts (core)",
            "pub_k2": "Published, $\\geq2$ cohorts",
            "op_k2": "Operator batch-corr., $\\geq2$ cohorts",
            "phi_k3": "Phikon discovery, $\\geq3$ cohorts"}
SET_ORDER = ["pub_k3", "pub_k4", "pub_k2", "op_k2", "phi_k3"]


def f3(x):
    return f"{x:.3f}"


def fp(p):
    # No p in this table lies within rounding distance of 0.05 or 0.15 (checked below).
    return f"{p:.3f}"


for p in d["p_auc"]:
    for thr in (0.05, 0.15):
        assert (p < thr) == (float(fp(p)) < thr), (p, thr)


def pct(x, nd=2):
    return f"{100 * x:.{nd}f}"


lines = []
A = lines.append
A("% Supplementary Table: post hoc BRCA frozen-section arm with set-level readout, governed by")
A("% review/POSTHOC_BRCA_TS_PRESPEC_2026-10-08.md (sidecar written 2026-10-08T01:04:30Z) and its")
A("% Amendment 1 (sidecar written 2026-10-08T16:57:40Z), both released publicly on GitHub before step 6.")
A("% Generated by make_supptable_brca_ts.py from")
A("% review/BRCA_TS_ARM_2026-10-08/setlevel/results/setlevel_result.csv (single local read-out).")
A("\\begin{table}[p]")
A("\\centering")
A("\\captionsetup{font={scriptsize,stretch=1.0}}")
A("\\caption{\\textbf{Post hoc BRCA frozen-section arm: per-gene and set-level readouts, diagnostic-slide "
  "gate and slide census.} Specified on 8 October 2026 (UTC) in a dated file released publicly before it "
  "ran (Supplementary Note~\\ref{snote:brcats}); post hoc, and reported whatever the result. "
  "\\textbf{(a)}~Per-gene readouts as published (significant = BH-FDR $<0.05$ and positive increment; "
  "$1{,}000$ permutations). No arm has a significant gene, so the percentage significant is $0\\%$ and the median increment of the significant genes is undefined in every row. Every TS patient is also a DX patient and no TS patient is missing relative "
  "to DX; the skip list is empty (no frozen-section slide failed download or extraction) and the GDC "
  "re-query reproduced the frozen $189$-file list, so there is no GDC-list difference. The DX gate "
  "compares the re-run with the published per-gene table and summary after both published files pass "
  "the published-file check (hash and summary values). "
  "\\textbf{(b)}~Set level: AUC of the BRCA increment of a discovery gene set against the other "
  "BRCA-tested genes among the $8{,}309$ genes tested in all five CPTAC-3 discovery cohorts ($8{,}073$ "
  "BRCA-tested), with the null mean$\\pm$s.d.\\ and the one-sided $p=(\\#\\{\\mathrm{null}\\geq"
  "\\mathrm{observed}\\}+1)/1{,}001$ from the same permutations; \\emph{Holm} = Holm-adjusted $p$ over "
  "the four secondary sets within each arm (descriptive); $\\rho$ = Spearman correlation of the "
  "discovery score (the gene's mean increment over the five discovery cohorts in the discovery analysis "
  "that defines the set) with the BRCA increment over the universe, and its one-sided permutation $p$ "
  "(descriptive; the three published sets share one score, so they share $\\rho$). Coverage = share of the set's genes that are "
  "BRCA-tested; no set fell below $50\\%$, so none is untestable. The TS-tile arm and every secondary "
  "set are reported here only. "
  "\\textbf{(c)}~Slide headers: apparent magnification (\\texttt{aperio.AppMag}) and microns per pixel; "
  "\\emph{Tile width} = $256$~px $\\times$ mpp at level~0, so a tile spans about $64~\\mu$m at "
  "$\\approx0.25~\\mu$m/px and about $128~\\mu$m at $\\approx0.5~\\mu$m/px (two-fold in width, four-fold "
  "in area). DX tile counts are from the full-density census (Amendment~1). Nothing was re-run, "
  "restricted or stratified by magnification.}")
A("\\label{tab:brcats}")
A("\\scriptsize")
A("\\setlength{\\tabcolsep}{3pt}")

# (a) per-gene
A("\\textbf{(a)} Per-gene readouts and DX gate\\\\[2pt]")
A("\\resizebox{\\textwidth}{!}{%")
A("\\begin{tabular}{lrrrrrrl}")
A("\\toprule")
A("Arm & Patients & Slides & Missing vs DX & Genes tested & Significant & Negative increment (\\%) & "
  "DX gate \\\\")
A("\\midrule")
for arm in ["ts", "ts_tile", "dx"]:
    s = summ[arm]
    c = cases[arm]
    g = ""
    if arm == "dx":
        mant, ex = f"{gate['max_abs_diff']:.1e}".split("e")
        g = f"{gate['tier']}; max $|\\Delta|={mant}\\times10^{{{int(ex)}}}$"
    A(f"{ARM_NAME[arm]} & {int(s['n_cases'])} & {c['n_slides']} & {len(c['missing_cases'])} & "
      f"{int(s['tested']):,} & {int(s['significant'])} & {pct(s['negative_frac_all'])} & {g} \\\\")
p = summ["dx_pub"]
pub_ok = "files pass check; summaries identical" if (gate["published_files_ok"] and gate["same_summary"]) else "check failed"
A(f"DX published & {int(p['n_cases'])} & 107 & --- & {int(p['tested']):,} & {int(p['significant'])} & "
  f"{pct(p['negative_frac_all'])} & {pub_ok} \\\\")
A("\\bottomrule")
A("\\end{tabular}}")
A("")
A("\\vspace{4pt}")

# (b) set level
A("\\textbf{(b)} Set-level readouts\\\\[2pt]")
A("\\resizebox{\\textwidth}{!}{%")
A("\\begin{tabular}{llrrrrrrr}")
A("\\toprule")
A("Arm & Set (genes in set file) & Selected / background & Coverage (\\%) & AUC & Null mean$\\pm$s.d. & "
  "$p$ (count) & Holm & $\\rho$ ($p_\\rho$) \\\\")
A("\\midrule")
for arm in ["ts", "dx", "ts_tile"]:
    A(f"\\multicolumn{{9}}{{l}}{{\\emph{{{ARM_NAME[arm]}}}}} \\\\")
    g = d[d["arm"] == arm].set_index("set")
    for sid in SET_ORDER:
        r = g.loc[sid]
        holm = "---" if pd.isna(r["p_auc_holm_secondary"]) else fp(r["p_auc_holm_secondary"])
        cnt = int(round(r["p_auc"] * 1001))
        A(f" & {SET_NAME[sid]} ({int(r['n_set_file_selected']):,}) & {int(r['n_selected']):,} / "
          f"{int(r['n_background']):,} & {pct(r['coverage_selected'], 1)} & {f3(r['auc_obs'])} & "
          f"{f3(r['auc_null_mean'])}$\\pm${f3(r['auc_null_sd'])} & {fp(r['p_auc'])} ({cnt}/1,001) & "
          f"{holm} & {f3(r['rho_obs'])} ({fp(r['p_rho'])}) \\\\")
A("\\bottomrule")
A("\\end{tabular}}")
A("")
A("\\vspace{4pt}")

# (c) slide census
A("\\textbf{(c)} Slide headers and tiles\\\\[2pt]")
A("\\begin{tabular}{lrrrr}")
A("\\toprule")
A("Arm & Apparent mag. & mpp ($\\mu$m/px) & Slides & Tile width ($\\mu$m) \\\\")
A("\\midrule")
for arm, qc in [("TS", qc_ts), ("DX", qc_dx)]:
    cnt = Counter(zip(qc["aperio.AppMag"].astype(int), qc["openslide.mpp-x"].round(4)))
    for (mag, mpp), n in sorted(cnt.items(), key=lambda kv: (-kv[0][0], kv[0][1])):
        A(f"{arm} & {mag}$\\times$ & {mpp:.4f} & {n} & {256 * mpp:.1f} \\\\")
    if arm == "TS":
        A("\\midrule")
A("\\bottomrule")
A("\\end{tabular}\\\\[3pt]")
ts_slide = qc_ts["n_tiles"]
dx_case = qc_dx.groupby("case")["n_tiles"].sum()
A("Tiles per slide, median (range): TS "
  f"{int(median(ts_slide)):,} ({int(ts_slide.min()):,}--{int(ts_slide.max()):,}); DX "
  f"{int(median(qc_dx['n_tiles'])):,} ({int(qc_dx['n_tiles'].min()):,}--{int(qc_dx['n_tiles'].max()):,}).\\\\")
A("Tiles per patient, median (range): TS "
  f"{int(median(pool['n_tiles'])):,} ({int(pool['n_tiles'].min()):,}--{int(pool['n_tiles'].max()):,}); DX "
  f"{int(median(dx_case)):,} ({int(dx_case.min()):,}--{int(dx_case.max()):,}).\\\\")
spc = Counter(pool["n_slides"])
A("TS slides per patient: "
  + "; ".join(f"{k} slide{'s' if k > 1 else ''} in {v} patients" for k, v in sorted(spc.items()))
  + f"; skipped slides: {len(skips)}.")
A("\\end{table}")

text = "\n".join(lines) + "\n"
(ROOT / "SuppTable_brca_ts.tex").write_bytes(text.encode("utf-8"))
print("wrote SuppTable_brca_ts.tex")
