"""Build SuppTable_c1ucec_sets.tex from server_export/results/c1_ucec_posthoc_sets/result.csv
(the single pre-specified run of review/POSTHOC_UCEC_C1_SETS_PRESPEC_2026-10-08.md)."""
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parent
d = pd.read_csv(ROOT / "server_export/results/c1_ucec_posthoc_sets/result.csv")

LABEL = {
    "S6": "S6 FFPE-only discovery (arm F)", "S1": "S1 operator, Batch-corr.",
    "S2": "S2 operator, Strictest", "S3": "S3 embedding medium, Corr.",
    "S4": "S4 TMT plex, Corr.", "S5": "S5 TMT plex, Strictest", "S7": "S7 Disqualified aliquots excl.\\ (arm Q)",
}


def f3(x):
    return f"{x:.3f}"


def fp(p):
    return f"{p:.3f}"


def row(sid, name, role):
    g = d[d["set"] == sid].set_index("arm")
    u, w, r = g.loc["unrestricted"], g.loc["within-operator"], g.loc["residualised"]
    shared = "" if pd.isna(u.get("overlap_with_published", float("nan"))) else f" ({int(u['overlap_with_published']):,})"
    holm = "" if role != "secondary" else fp(u["p_set_holm_secondary"])
    return (f"{name} & {int(u['n_selected']):,}{shared} & {f3(u['auc_obs'])} & "
            f"{f3(u['auc_null_mean'])}$\\pm${f3(u['auc_null_sd'])} ({fp(u['p_auc'])}) & "
            f"{f3(w['auc_null_mean'])}$\\pm${f3(w['auc_null_sd'])} ({fp(w['p_auc'])}) & "
            f"{f3(w['margin'])} & {f3(r['auc_obs'])} ({fp(r['p_auc'])}) & {holm} \\\\")


lines = []
A = lines.append
A("% Supplementary Table: post hoc C1-UCEC re-reads with alternative discovery selection sets,")
A("% governed by review/POSTHOC_UCEC_C1_SETS_PRESPEC_2026-10-08.md, released publicly on GitHub")
A("% (commit 8a70293, tag c1-ucec-posthoc-sets-prespec-2026-10-08) before the single run.")
A("% Generated by make_supptable_c1ucec_sets.py from server_export/results/c1_ucec_posthoc_sets/result.csv.")
A("\\begin{table}[p]")
A("\\centering")
A("\\captionsetup{font={scriptsize,stretch=1.0}}")
A("\\caption{\\textbf{Post hoc re-reads of the UCEC confirmatory test with alternative discovery "
  "selection sets.} Specified on 8 October 2026 in a dated file released publicly before the single run "
  "(Supplementary Note~\\ref{snote:c1posthoc}); post hoc, and reported whatever the result. Each row "
  "re-reads the published confirmatory increments ($138$ patients) with a different discovery selection "
  "set, against every other usable confirmatory gene tested in that discovery analysis. "
  "\\emph{Selected (shared)} = genes in the confirmatory universe (of which in the published "
  "$2{,}566$-gene set). Nulls: $1{,}000$ patient$\\leftrightarrow$slide permutations, unrestricted or "
  "within scanning operator (mean$\\pm$s.d., one-sided $p$; floor $0.001$); \\emph{Margin} = AUC minus "
  "the within-operator null mean; \\emph{Resid.} = morphology components residualised on the twelve "
  "largest operator levels (descriptive). \\emph{Holm} = Holm-adjusted $\\max(p_{\\mathrm{unrestr.}}, "
  "p_{\\mathrm{within}})$ over the six secondary sets; a set holds if it is below $0.05$. "
  "\\emph{-new} rows: the genes of a set that are not in the published set, against the universe minus "
  "the whole set (descriptive). The embedding-medium Strictest estimator selects no UCEC gene and "
  "cannot be tested. S1 and S2 had been computed before the specification was written "
  "(disclosed there); every other row was blind.}")
A("\\label{tab:c1ucecsets}")
A("\\scriptsize")
A("\\setlength{\\tabcolsep}{2.5pt}")
A("\\resizebox{\\textwidth}{!}{%")
A("\\begin{tabular}{lrrrrrrr}")
A("\\toprule")
A("Set & Selected (shared) & AUC & Unrestr.\\ null ($p$) & Within-op.\\ null ($p$) & Margin & "
  "Resid.\\ AUC ($p$) & Holm \\\\")
A("\\midrule")
A("\\multicolumn{8}{l}{\\emph{Primary}} \\\\")
A(row("S6", LABEL["S6"], "primary"))
A(row("S6new", "\\quad S6-new", "descriptive"))
A("\\multicolumn{8}{l}{\\emph{Secondary family}} \\\\")
for s in ["S1", "S2", "S3", "S4", "S5", "S7"]:
    A(row(s, LABEL[s], "secondary"))
A("\\multicolumn{8}{l}{\\emph{Genes not in the published set (descriptive)}} \\\\")
for s in ["S1", "S2", "S3", "S4", "S5", "S7"]:
    A(row(s + "new", f"\\quad {s}-new", "descriptive"))
A("\\bottomrule")
A("\\end{tabular}}")
A("\\end{table}")
A("")
A("\\begin{table}[p]")
A("\\centering")
A("\\captionsetup{font={scriptsize,stretch=1.0}}")
A("\\caption{\\textbf{Reference for the FFPE-only set: 19 discovery re-derivations that each remove 22 "
  "random patients.} Same confirmatory matrix, statistic and nulls as S6, ordered by margin over the "
  "within-operator null, the pre-specified comparison. S6 is shown in bold.}")
A("\\label{tab:c1ucecsetsref}")
A("\\scriptsize")
A("\\begin{tabular}{lrrrrr}")
A("\\toprule")
A("Arm & Selected & AUC & Within-op.\\ null & Margin & $p$ \\\\")
A("\\midrule")
ref = d[(d["arm"] == "within-operator") & d["role"].isin(["primary", "reference"])].sort_values("margin")
for _, r in ref.iterrows():
    name = "\\textbf{S6}" if r["set"] == "S6" else r["set"]
    cells = [name, f"{int(r['n_selected']):,}", f3(r["auc_obs"]),
             f"{f3(r['auc_null_mean'])}$\\pm${f3(r['auc_null_sd'])}", f3(r["margin"]), fp(r["p_auc"])]
    if r["set"] == "S6":
        cells = [cells[0]] + [f"\\textbf{{{c}}}" for c in cells[1:]]
    A(" & ".join(cells) + " \\\\")
A("\\bottomrule")
A("\\end{tabular}")
A("\\end{table}")
(ROOT / "SuppTable_c1ucec_sets.tex").write_bytes(("\n".join(lines) + "\n").encode("utf-8"))
print("wrote SuppTable_c1ucec_sets.tex")
