"""sim_section7_tables.py -- compact markdown tables for DERIVATION.md section 7 from the
synthetic grids (sim_grid_v2_*.csv), the mixture replicates (sim_mixture_*.csv) and the
batch-null study (sim_batchnull.csv).  Synthetic results only.
Usage: python sim_section7_tables.py > section7_tables.md"""
import os
import sys

import numpy as np
import pandas as pd

HERE = os.path.dirname(os.path.abspath(__file__))


def load(name):
    p = os.path.join(HERE, name)
    if not os.path.exists(p):
        print(f"<!-- missing {name} -->")
        return None
    d = pd.read_csv(p)
    if "fX" in d.columns:
        d["fX"] = d["fX"].fillna(-1)
    return d


def hyplabel(r):
    return f"mix f_X={r.fX:.1f}" if r.hyp == "mix" else {"noise": "H_noise", "post": "H_post", "err": "H_err"}[r.hyp]


HYP_ORDER = [("noise", -1), ("mix", 0.5), ("mix", 0.3), ("mix", 0.1), ("post", -1), ("err", -1)]


def grid_table(d, R2, cell, title, lams=(0.5, 0.6, 0.7, 0.8, 0.9), deltas=(0.1, 0.2)):
    cols = [(l, dl) for dl in deltas for l in lams]
    print(f"\n**{title}** (R2_rna = {R2}; columns: population increment Δ_p then λ; '·' = no gene selected; "
          f"'†' = hypothesis cannot reach Δ_p at this λ even with ρ = 0.95, run at the cap)\n")
    print("| hypothesis | " + " | ".join(f"Δ={dl} λ={l}" for l, dl in cols) + " |")
    print("|---|" + "---|" * len(cols))
    for hyp, fX in HYP_ORDER:
        row = []
        for l, dl in cols:
            q = d[(d.hyp == hyp) & (np.isclose(d.fX, fX)) & (np.isclose(d.lam, l)) & (np.isclose(d.delta_target, dl)) & (np.isclose(d.R2rna, R2))]
            if len(q) == 0:
                row.append("")
                continue
            r = q.iloc[0]
            s = cell(r)
            if not bool(r.feasible):
                s = s + "†"
            row.append(s)
        lab = f"mix f_X={fX}" if hyp == "mix" else {"noise": "H_noise", "post": "H_post", "err": "H_err"}[hyp]
        print(f"| {lab} | " + " | ".join(row) + " |")


def f(x, nd=2, plus=False):
    if x is None or (isinstance(x, float) and not np.isfinite(x)):
        return "·"
    return f"{x:+.{nd}f}" if plus else f"{x:.{nd}f}"


def main():
    print("# Section 7 tables (generated by sim_section7_tables.py; synthetic data only)\n")
    for name, lab in (("sim_grid_v2_n100_G200.csv", "n = 100, G = 200"), ("sim_grid_v2_n60_G200.csv", "n = 60, G = 200"),
                      ("sim_grid_v2_n100_G40.csv", "n = 100, G = 40")):
        d = load(name)
        if d is None:
            continue
        print(f"\n## Grid {lab} (B = 200 selection draws, B = 200 joint-null draws, one cohort per cell)\n")
        for R2 in (0.3, 0.1):
            grid_table(d, R2, lambda r: f(r.sel_rate, 2), f"7.{lab}: selection rate n_sel/G (FDR<0.05 & Δ̂>0)")
            grid_table(d, R2, lambda r: f(r.Nc_set_z, 0, True) if np.isfinite(r.get("Nc_set_z", np.nan)) else "·",
                       f"7.{lab}: set-level z of N_c,set = Σ ρ̂·corr(r̂_p, M) under the joint null")
            grid_table(d, R2, lambda r: (f(r.theta_set_sel, 2, True) + "/" + f(r.theta_pop, 2, True)) if np.isfinite(r.theta_set_sel) else "·",
                       f"7.{lab}: θ_set under selection / population θ (winner's-curse calibration)")
            grid_table(d, R2, lambda r: (f(r.S_cross_mean_sel, 2, True) + " (z" + f(r.S_cross_agg_z, 0, True) + ")") if np.isfinite(r.S_cross_mean_sel) else "·",
                       f"7.{lab}: S_cross mean on selected genes (set-level z vs joint null)")
        # over-rejection of the covariance form vs correlation form under H_post
        q = d[(d.hyp == "post") & (d.n_sel >= 10)]
        if len(q):
            print(f"\n**Per-gene two-sided rejection at nominal 5% on selected genes under H_post ({lab}; {len(q)} cells with n_sel ≥ 10):** "
                  f"covariance form N = ρ̂·cov(r̂_p, M): mean {q.N_pg_rej_sel.mean():.3f} (range {q.N_pg_rej_sel.min():.2f}–{q.N_pg_rej_sel.max():.2f}); "
                  f"correlation form N_c = ρ̂·corr(r̂_p, M): mean {q.N_corr_pg_rej_sel.mean():.3f} (range {q.N_corr_pg_rej_sel.min():.2f}–{q.N_corr_pg_rej_sel.max():.2f}). "
                  f"Set-level |z| under H_post: cov form median {q.N_set_z.abs().median():.2f}, max {q.N_set_z.abs().max():.2f}; corr form median {q.Nc_set_z.abs().median():.2f}, max {q.Nc_set_z.abs().max():.2f}.")
        ok = d[d.n_sel >= 10]
        print("\n**Per-hypothesis summary over cells with n_sel ≥ 10:**\n")
        print("| hypothesis | cells | Nc_set z min/med/max | S z min/med/max | θ_set min/med/max | θ_set/θ_pop med | λ̂_noise med |")
        print("|---|---|---|---|---|---|---|")
        for hyp, fX in HYP_ORDER:
            g = ok[(ok.hyp == hyp) & np.isclose(ok.fX, fX)]
            if len(g) == 0:
                continue
            ratio = (g.theta_set_sel / g.theta_pop).replace([np.inf, -np.inf], np.nan)
            lab2 = f"mix f_X={fX}" if hyp == "mix" else {"noise": "H_noise", "post": "H_post", "err": "H_err"}[hyp]
            print(f"| {lab2} | {len(g)} | {g.Nc_set_z.min():+.1f}/{g.Nc_set_z.median():+.1f}/{g.Nc_set_z.max():+.1f} | "
                  f"{g.S_cross_agg_z.min():+.1f}/{g.S_cross_agg_z.median():+.1f}/{g.S_cross_agg_z.max():+.1f} | "
                  f"{g.theta_set_sel.min():+.2f}/{g.theta_set_sel.median():+.2f}/{g.theta_set_sel.max():+.2f} | "
                  f"{ratio.median():.2f} | {g.lamhat_noise_sel.median():.2f} |")

    # ---------------- mixture replicates ----------------
    dm = load("sim_mixture_main.csv")
    if dm is not None:
        print("\n## Mixture cohorts: G = 2,000 genes, 20% carrying the signal, n = 100, replicate seeds\n")
        print("| hypothesis | R2 | λ | Δ_p | reps | n_sel (null) | FDR | θ_pop | θ oracle (signal genes) | θ_set,sel | θ_set,sel∩signal | θ_pc,sel | θ_set,all | Nc_sel z | Nc_all z | S_sel z | class (sel) |")
        print("|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|")
        for (hyp, R2, lam, dl, fX), g in dm.groupby(["hyp", "R2rna", "lam", "delta_target", "fX"], sort=False):
            lab = f"mix f_X={fX:.1f}" if hyp == "mix" else {"noise": "H_noise", "post": "H_post", "err": "H_err"}[hyp]
            cls = g.class_sel.value_counts().to_dict()
            cls_s = ", ".join(f"{k.split('_',1)[0]}×{v}" for k, v in cls.items())
            feas = "" if bool(g.feasible.iloc[0]) else "†"

            def ms(col, nd=2):
                return f"{g[col].mean():+.{nd}f}±{g[col].std():.{nd}f}" if col in g else "·"

            print(f"| {lab}{feas} | {R2} | {lam} | {dl} | {len(g)} | {g.n_sel.mean():.0f} ({g.n_sel_null.mean():.0f}) | {g.fdr_realised.mean():.2f} | "
                  f"{g.theta_pop.iloc[0]:+.2f} | {ms('theta_set_signal')} | {ms('theta_set_sel')} | {ms('theta_set_sel_signalonly')} | "
                  f"{ms('theta_pc_sel')} | {ms('theta_set_all')} | {ms('Nc_sel_z',1)} | {ms('Nc_all_z',1)} | {ms('S_sel_z',1)} | {cls_s} |")
        q = dm[dm.hyp == "post"]
        if len(q):
            print(f"\nPer-gene 5% two-sided rejection under H_post, selected genes: cov form {q.N_pg_rej_sel.mean():.3f}, corr form {q.Nc_pg_rej_sel.mean():.3f}; "
                  f"on pure-null genes (all hypotheses): cov form {dm.N_pg_rej_null.mean():.3f}, corr form {dm.Nc_pg_rej_null.mean():.3f}.")
        print("\n**Classification counts (reading rule of §7.4 applied to the selected set, Nc_sel z and θ_set,sel):**\n")
        ct = pd.crosstab(dm.apply(lambda r: f"{hyplabel(r)} λ={r.lam} Δ={r.delta_target} R2={r.R2rna}", axis=1), dm.class_sel)
        print(ct.to_markdown())
    ds = load("sim_mixture_size.csv")
    if ds is not None:
        print("\n## Set-size dependence (R2 = 0.3; G and signal fraction varied; 3 replicates)\n")
        print("| hypothesis | G | π_1 | n_sel | θ_pop | θ_set,sel mean ± sd | θ_set,all mean ± sd | jackknife SE | Nc_sel z | class |")
        print("|---|---|---|---|---|---|---|---|---|---|")
        for (hyp, G, pi1, fX), g in ds.groupby(["hyp", "G", "pi1", "fX"], sort=False):
            lab = f"mix f_X={fX:.1f}" if hyp == "mix" else {"noise": "H_noise", "post": "H_post", "err": "H_err"}[hyp]
            cls = ", ".join(f"{k.split('_',1)[0]}×{v}" for k, v in g.class_sel.value_counts().to_dict().items())
            print(f"| {lab} | {G} | {pi1} | {g.n_sel.mean():.0f} | {g.theta_pop.iloc[0]:+.2f} | {g.theta_set_sel.mean():+.3f} ± {g.theta_set_sel.std():.3f} | "
                  f"{g.theta_set_all.mean():+.3f} ± {g.theta_set_all.std():.3f} | {g.theta_set_sel_jkse.mean():.3f} | {g.Nc_sel_z.mean():+.1f} | {cls} |")
    # ---------------- batch null ----------------
    db = load("sim_batchnull.csv")
    if db is not None:
        print("\n## Operator-batch structure: unrestricted vs within-operator null (n = 100, G = 200, 12 operators + 10 singletons, R2 = 0.3, λ = 0.5, Δ_p = 0.10)\n")
        print("| config (ν_W, ν_e, ν_P, ν_X) | hypothesis | reps | n_sel | θ_pop | θ_set raw | θ_set resid-W | Nc z unrestricted | Nc z stratified | D z unres/strat | S mean | class unres | class strat |")
        print("|---|---|---|---|---|---|---|---|---|---|---|---|---|")
        for (cfg, hyp), g in db.groupby(["config", "hyp"], sort=False):
            lab = {"noise": "H_noise", "post": "H_post", "err": "H_err", "mix": "mix f_X=0.3"}[hyp]
            cfgs = f"{cfg} ({g.nu_W.iloc[0]},{g.nu_e.iloc[0]},{g.nu_P.iloc[0]},{g.nu_X.iloc[0]})"
            cu = ", ".join(f"{k.split('_',1)[0]}×{v}" for k, v in g.class_unres.value_counts().to_dict().items())
            cs = ", ".join(f"{k.split('_',1)[0]}×{v}" for k, v in g.class_strat.value_counts().to_dict().items())
            print(f"| {cfgs} | {lab} | {len(g)} | {g.n_sel.mean():.0f} | {g.theta_pop.iloc[0]:+.2f} | {g.theta_set_sel.mean():+.2f}±{g.theta_set_sel.std():.2f} | "
                  f"{g.theta_set_sel_resid.mean():+.2f}±{g.theta_set_sel_resid.std():.2f} | {g.Nc_z_unres.mean():+.1f}±{g.Nc_z_unres.std():.1f} | "
                  f"{g.Nc_z_strat.mean():+.1f}±{g.Nc_z_strat.std():.1f} | {g.D_z_unres.mean():+.0f}/{g.D_z_strat.mean():+.0f} | {g.S_mean_sel.mean():+.2f} | {cu} | {cs} |")


if __name__ == "__main__":
    main()
